MVCMusicStoreApplication-master/MVCMusicStoreApplication/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCMusicStoreApplication.Models;

namespace MVCMusicStoreApplication.Controllers
{
    public class ShoppingCartController : Controller
    {
        MVCMusicStoreDB db = new MVCMusicStoreDB();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            ShoppingCart cart = ShoppingCart.GetCart(this.HttpContext);

            ShoppingCartViewModel vm = new ShoppingCartViewModel()
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetCartTotal()
            };
            return View(vm);
        }

        //GET: ShoppingCart/AddToCart/7
        public ActionResult AddToCart(int id )
        {

           // ShoppingCart cart =new  ShoppingCart();
           ShoppingCart cart =ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(id);

            return RedirectToAction("Index");
        }
        //Post: ShoppingCart/RemoveFromCart/7
        [HttpPost]
        public ActionResult RemoveFromCart(int id )
        {
            ShoppingCart cart = ShoppingCart.GetCart(this.HttpContext);

            Album album = db.Carts.SingleOrDefault(c => c.RecordId == id).AlbumSelected;

            int newItemCount = cart.RemoveFromCart(id);

            cart.RemoveFromCart(id);

            ShoppingCartRemoveViewModel vm = new ShoppingCartRemoveViewModel()
            {
                DeleteId = id,
            CartTotal = cart.GetCartTotal(),
            ItemCount = newItemCount,
            Message = album.Title + " has been removed from the cart"

            };
            return Json(vm);
        }
    }
}

MVCMusicStoreApplication-master/MVCMusicStoreApplication/Controllers/StoreManagerController.cs
  using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCMusicStoreApplication.Models;

namespace MVCMusicStoreApplication.Controllers
{
    public class StoreManagerController : Controller
    {
        private MVCMusicStoreDB db = new MVCMusicStoreDB();



        public ActionResult DailyDeal()
        {
        var album = GetDailyDeal();
        return PartialView("_DailyDeal", album);
           }
        private object GetDailyDeal()
        {
            // Get random album
            var album = db.Albums
                .OrderBy(async => System.Guid.NewGuid())
                .First();

            //Apply discount
            album.Price *= 0.5m;
            return album;
    
}
public ActionResult ArtistSearch(string q)
        {
            var artists = GetArtists(q);
            return PartialView(artists);

        }
        private List<Artist> GetArtists(string searchString)
        {
            return db.Artists
            .Where(a => a.Name.Contains(searchString))
                .ToList();
                }











        // GET: StoreManager
        public ActionResult Index()
        {
            

            var albums = db.Albums.Include(a => a.Artist).Include(a => a.Genre);
            return View(albums.ToList());
        }

        // GET: StoreManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: StoreManager/Create
        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name");
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name");
            return View();
        }

        // POST: StoreManager/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // GET: StoreManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // POST: StoreManager/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // GET: StoreManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: StoreManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCMusicStoreApplication-master/MVCMusicStoreApplication/Views/StoreManager/Create.cshtml
@model MVCMusicStoreApplication.Models.Album

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "GenreId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumArtUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumArtUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumArtUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCMusicStoreApplication-master/MVCMusicStoreApplication/Views/StoreManager/Delete.cshtml
@model MVCMusicStoreApplication.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumArtUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumArtUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCMusicStoreApplication-master/MVCMusicStoreApplication/Views/StoreManager/Details.cshtml
@model MVCMusicStoreApplication.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumArtUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumArtUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AlbumId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCMusicStoreApplication-master/MVCMusicStoreApplication/Views/StoreManager/Edit.cshtml
@model MVCMusicStoreApplication.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AlbumId)

        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "GenreId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumArtUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumArtUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumArtUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCMusicStoreApplication-master/MVCMusicStoreApplication/Views/StoreManager/Index.cshtml
@model IEnumerable<MVCMusicStoreApplication.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div id="dailydeal">
    @Ajax.ActionLink("CLICK HERE TO SEE TODAY'S SPECIAL!",
        "DailyDeal",
        null,
        new AjaxOptions
        {
            UpdateTargetId = "dailydeal",
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "GET"
    },
        new { @class = "btn btn-primary" })
</div>

<div class="panel panel-primary">
    <div class=" panel-heading">Artist search</div>
    <div  class=" panel-body">
        @using (Ajax.BeginForm("ArtistSearch", "StoreManager", new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "GET",
            OnFailure = "searchFailed",
            LoadingElementId = "ajax-loader.gif",
            UpdateTargetId = "searchresults"
        }))
        {
           <input type="text" name=" q"? />
            <input type="submit" value=" search"/>
            <img id=" ajax-loader"
                 src=" @Url.Content("~/Content/Images/ajax-loader.gif")"
                 style="display:none"/>


        }
        <div id=" searchresults"></div>
        </div>
    </div>


        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Artist.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Genre.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AlbumArtUrl)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Artist.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Genre.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AlbumArtUrl)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.AlbumId }) |
                        @Html.ActionLink("Details", "Details", new { id = item.AlbumId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.AlbumId })
                    </td>
                </tr>
            }

        </table>

        @section Scripts{


            <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
            <script src="~/Scripts/Apps/MusicScripts.js"></script>

        }

MVCMusicStoreApplication-master/MVCMusicStoreApplication/Views/StoreManager/_ArtistSearch.cshtml
@model IEnumerable<MVCMusicStoreApplication.Models.Artist>

<div id=" searchresults">
    <ul>
        >@foreach(var item in Model)
        {
            <li>@item.Name</li>

        }
        
    </ul>

    </div>

MVCMusicStoreApplication-master/MVCMusicStoreApplication/Views/StoreManager/_DailyDeal.cshtml
@model MVCMusicStoreApplication.Models.Album
    


<div class="panel panel-primary">
    <div class=" panel-heading">

        <h3 class=" panel-title">Your daily deal:@Model.Title</h3>

    </div>
    <div  class=" panel-body">

        <p>
            <img alt=" @Model.Title" src=" @Url.Content(Model.AlbumArtUrl)"/>
        </p>

        <div id="album-details">
            <p>
                <em>Artist:</em>
                @Model.Artist.Name
            </p>

            <p>
                <em>Price:</em>
                @String.Format("{0:F}",Model.Price)
            </p>
            @Html.ActionLink("Add to Cart", "AddToCart", "ShoppingCart",
           new { id = Model.AlbumId},
           new { @class ="btn btn-primary"})

    </div>
</div>
    </div>











</div>